version: 2.1

orbs:
  slack: circleci/slack@4.3.0

executors:
  macos-executor:
    macos:
      xcode: 12.4.0

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle --clean
      - save_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
  setup_maptile:
    steps:
      - run:
          command: |
            [ ! -f "bathymetry/TileAPI-Info.plist" ] && plutil -replace baseUrl -string $IOS_MAPTILE_BASE_URL bathymetry/TileAPI-Example-Info.plist
            [ ! -f "bathymetry/TileAPI-Info.plist" ] && cp bathymetry/TileAPI-Example-Info.plist bathymetry/TileAPI-Info.plist
  setup_mapbox:
    steps:
      - run:
          command: |
            [ ! -d "Frameworks" ] && mkdir Frameworks
            [ ! -f "mapbox.zip" ] && curl -o mapbox.zip $IOS_MAPBOX_DOWNLOAD_URL
            [ ! -d "mapbox" ] && unzip mapbox.zip -d mapbox
            [ ! -d "Frameworks/Mapbox.framework" ] && cp -r mapbox/dynamic/Mapbox.framework Frameworks/Mapbox.framework
            [ ! -d "Frameworks/MapboxMobileEvents.framework" ] && cp -r mapbox/dynamic/MapboxMobileEvents.framework Frameworks/MapboxMobileEvents.framework
            [ ! -f "bathymetry/Mapbox-Info.plist" ] && plutil -replace MGLMapboxAccessToken -string $IOS_MAPBOX_ACCESS_TOKEN bathymetry/Mapbox-Example-Info.plist
            [ ! -f "bathymetry/Mapbox-Info.plist" ] && cp bathymetry/Mapbox-Example-Info.plist bathymetry/Mapbox-Info.plist
  slack_notify_fail:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
  slack_notify_success:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  unit-tests:
    executor:
      name: macos-executor
    steps:
      - setup
      - setup_maptile
      - setup_mapbox
      - run: bundle exec fastlane unit_tests
      - store_test_results:
          path: unit_test_output
      - store_artifacts:
          path: unit_test_output
          destination: scan-output
      - slack_notify_fail
  snapshot-tests-on-iphone12promax:
    executor:
      name: macos-executor
    steps:
      - setup
      - setup_maptile
      - setup_mapbox
      - run: bundle exec fastlane snapshot_tests_on_iphone12promax
      - store_test_results:
          path: snapshot_test_output
      - store_artifacts:
          path: snapshot_test_output
          destination: scan-output
      - slack_notify_fail
  snapshot-tests-on-ipodtouch7thgeneration:
    executor:
      name: macos-executor
    steps:
      - setup
      - setup_maptile
      - setup_mapbox
      - run: bundle exec fastlane snapshot_tests_on_ipodtouch7thgeneration
      - store_test_results:
          path: snapshot_test_output
      - store_artifacts:
          path: snapshot_test_output
          destination: scan-output
      - slack_notify_fail
  slack-notify:
    executor:
      name: macos-executor
    steps:
      - run: echo "succeeded"
      - slack_notify_fail
      - slack_notify_success

workflows:
  version: 2.1
  test-and-upload:
    jobs:
      - unit-tests:
          context: bathymetric-cam-ios
          filters:
            branches:
              only: main
      - snapshot-tests-on-iphone12promax:
          context: bathymetric-cam-ios
          filters:
            branches:
              only: main
      - snapshot-tests-on-ipodtouch7thgeneration:
          context: bathymetric-cam-ios
          filters:
            branches:
              only: main
      - slack-notify:
          requires:
            - unit-tests
            - snapshot-tests-on-iphone12promax
            - snapshot-tests-on-ipodtouch7thgeneration
          context: bathymetric-cam-ios
          filters:
            branches:
              only: main
